name: beta

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Get Version
        id: version
        run: |
          export NODE_VERSION=$(curl -sSL https://nodejs.org/dist/latest-v16.x/ | grep linux-x64.tar.gz | sed -n "s/.*>node-v\(.*\)-linux.*<.*/\1/p")
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
          echo "Version: ${NODE_VERSION}"
      - name: Build
        run: |
          docker buildx build \
             --push \
             --platform linux/arm64,linux/amd64 \
              --build-arg NODE_VERSION="${NODE_VERSION}" \
             -f Dockerfile \
             -t truemark/node:beta-${NODE_VERSION} \
             -t truemark/node:beta-16 \
             -t truemark/node:beta \
             .
          ocker buildx build \
             --push \
             --platform linux/arm64,linux/amd64 \
              --build-arg NODE_VERSION="${NODE_VERSION}" \
             -f alpine.Dockerfile \
             -t truemark/node:beta-${NODE_VERSION}-alpine \
             -t truemark/node:beta-16-alpine \
             -t truemark/node:beta-alpine \
             .
